name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:

  check:
    name: Check
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [stable, beta, nightly]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.toolchain }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        toolchain: [stable, beta, nightly]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.toolchain }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  test-windows:
    name: Test Windows
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    runs-on: windows-latest
    env:
      SQLITE_URL: "https://www.sqlite.org/2022/sqlite-amalgamation-3400100.zip"
      PKG_CONFIG_PATH: "C:/sqlite3/sqlite-amalgamation-3400100/"
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.toolchain }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: install pkg-config, download and extract sqlite amalgamation, setup pkg-config file for sqlite3
        run: |
          choco install -y --no-progress --allow-empty-checksums --fail-on-stderr pkgconfiglite
          mkdir C:\sqlite3\
          curl $env:SQLITE_URL -o C:\sqlite3\sqlite3.zip
          Expand-Archive C:\sqlite3\sqlite3.zip -DestinationPath C:\sqlite3\
          @"
          Name: sqlite3
          Description: sqlite3 amalgamation
          Version: 3.40.1
          Cflags: -I${env:PKG_CONFIG_PATH}
          Libs:
          "@ > $env:PKG_CONFIG_PATH\sqlite3.pc

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
